### PR TITLE
Note component, integrated into App, with App cleaned up

### PR DESCRIPTION
**Pull request by chadcrume**

### CODE REVIEW

**Comment by chadcrume** [comment]
@alvarix , let me know if it's okay to merge this. I'll move on to a NodeList component after.

**Review by alvarix — APPROVED** [review]
Heya, looks great. 
We'll have to merge App. I forget the sequence. 

Two questions:

1. devtools - is that to make the browser extension work?
2. you committed yarn.lock - can you brief me what this does?

**Comment by chadcrume** [comment]
devtools — good catch, I'm not even sure how that got in there. Removed.
It's used when you use a non-standard browser that can't install the
browser extension for vue devtools.

yarn.lock — https://github.com/yarnpkg/yarn/issues/1583

Oh, oops.  I was going to merge my PR but ended up merging your's instead.
So, now I'll have to review it retroactively, and then I'll pull main into
my branch, resolve overlap with your App changes, then merge my PR. Gotta
run now, so I'll do that later.

**Comment by chadcrume** [comment]
Merged main including AddNote, and reconciled App

**Pull request merged**
